In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/stp-dataset/2DEVEA_pca_cat.csv
/kaggle/input/stp-dataset/DIFOX-24607888 (1).csv
/kaggle/input/stp-dataset/cid_export_04072023.csv
/kaggle/input/stp-dataset/EET_DGF (1).csv
/kaggle/input/stp-dataset/argor10072024 (1).csv
/kaggle/input/stp-dataset/Supplies24_30062023.csv
/kaggle/input/stp-dataset/travion.csv
/kaggle/input/stp-dataset/Arles (1).csv
/kaggle/input/stp-dataset/imcopex.csv
/kaggle/input/stp-dataset/Copaco.csv
/kaggle/input/stp-dataset/1DGFTECHNOLOGIE_mgf_cat.csv
/kaggle/input/stp-dataset/TOPUS_STOCKLIST_DGF (2).csv
/kaggle/input/stp-dataset/eparts.csv
/kaggle/input/stp-dataset/tarox (1).csv
/kaggle/input/stp-dataset/dexxon (1).csv
/kaggle/input/stp-dataset/FlexIT (1).csv
/kaggle/input/stp-dataset/1346094 (1).csv
/kaggle/input/stp-dataset/axro.csv
/kaggle/input/stp-dataset/terra.csv
/kaggle/input/katia-data/Data1 (1).csv
/kaggle/input/part2-icecat/132234_FR.csv

In [2]:
import pandas as pd

file_path = r"/kaggle/input/stp-dataset/1DGFTECHNOLOGIE_mgf_cat.csv"

# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        DGFTECH = pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'DGFTECH' in locals():
    print(DGFTECH.info())
else:
    print("Failed to load the file with the provided encodings.")

Error with utf-8 encoding: 'utf-8' codec can't decode byte 0xe9 in position 1230: invalid continuation byte
File successfully loaded with ISO-8859-1 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 14 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   CodeArticleWeb                        10178 non-null  object
 1   CodeArticle                           10178 non-null  object
 2   RefFournisseur                        10178 non-null  object
 3   GenCode                               10131 non-null  object
 4   Designation_Longue                    10178 non-null  object
 5   Groupe                                10177 non-null  object
 6   Marque                                10178 non-null  object
 7   Stock                                 10178 non-null  int64
 8   PrixHT_sans_ecop_et_sans_sorecop      10178 non-null  float64
 9   Ecopart_HT                            10178 non-null  float64
 10  Sorecop_HT                            10178 non-null  float64
 11  PrixHT_comprenant_Ecopart_et_Sorecop  10178 non-null  float64
 12  PrixPublic_HT                         10178 non-null  float64
 13  Poids                                 10178 non-null  float64
dtypes: float64(6), int64(1), object(7)
memory usage: 1.1+ MB
None

In [3]:
DGFTECH.head(3)

,CodeArticleWeb,CodeArticle,RefFournisseur,GenCode,Designation_Longue,Groupe,Marque,Stock,PrixHT_sans_ecop_et_sans_sorecop,Ecopart_HT,Sorecop_HT,PrixHT_comprenant_Ecopart_et_Sorecop,PrixPublic_HT,Poids
0,0-32LS03CBU,0-32LS03CBU,TQ32LS03CBUXXC,8806094915822,TV SAMSUNG The Frame 32'' 2023 TQ32LS03CBUXXC,TELEVISION,SAMSUNG,12,503.02,3.33,0.0,506.35,0.0,7.9
1,0-55LST7TCU,0-55LST7TCU,QE55LST7TCUXXC,8806092207356,TV SAMSUNG 55 THE TERRACE QLED 4K SMART TV EXT...,TELEVISION,SAMSUNG,2,3323.00,10.00,0.0,3333.00,0.0,37.3
2,0-65LST7TCU,0-65LST7TCU,QE65LST7TCUXXC,8806092213074,TV SAMSUNG 65 THE TERRACE QLED 4K SMART TV EXT...,TELEVISION,SAMSUNG,1,4154.00,10.00,0.0,4164.00,0.0,49.6

In [4]:
 DGFTECH = DGFTECH[['CodeArticle', 'Groupe', 'Marque', 'Designation_Longue', 
                          'RefFournisseur', 'Stock', 'PrixHT_comprenant_Ecopart_et_Sorecop']]

In [5]:
columns_rename=['Ref_produit','Categorie','Marque','Description','Ref_fournisseur','Quantite','Prix']

In [6]:
old_names = ['CodeArticle', 'Groupe', 'Marque', 'Designation_Longue', 
             'RefFournisseur', 'Stock', 'PrixHT_comprenant_Ecopart_et_Sorecop']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
DGFTECH  = DGFTECH .rename(columns=rename_dict)

In [7]:
DGFTECH.head(3)

,Ref_produit,Categorie,Marque,Description,Ref_fournisseur,Quantite,Prix
0,0-32LS03CBU,TELEVISION,SAMSUNG,TV SAMSUNG The Frame 32'' 2023 TQ32LS03CBUXXC,TQ32LS03CBUXXC,12,506.35
1,0-55LST7TCU,TELEVISION,SAMSUNG,TV SAMSUNG 55 THE TERRACE QLED 4K SMART TV EXT...,QE55LST7TCUXXC,2,3333.00
2,0-65LST7TCU,TELEVISION,SAMSUNG,TV SAMSUNG 65 THE TERRACE QLED 4K SMART TV EXT...,QE65LST7TCUXXC,1,4164.00

In [8]:
file_path = r"/kaggle/input/stp-dataset/1346094 (1).csv"
# Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
df1 = pd.read_csv(file_path)
df1.head(7)

,Part_number,Application,Type,Subtype0,Subtype1,Description,Stock_level,Price_EUR,RRP_EUR,Brand,Updated,Ean_number,Equivalent Part Number
0,00PA474,Lenovo ThinkPad T460s,Laptop,Keyboard,Unknown,Backlit Keyboard (Portuguese),1,40.78,97.88,2-Power,,NaN,00PA556
1,00PA556,Lenovo ThinkPad T460s,Laptop,Keyboard,Unknown,Backlit Keyboard (Portuguese),1,40.78,97.88,2-Power,,NaN,NaN
2,1200G-2USB-1,,Peripheral,Barcode Scanner,USB,Voyager 1200g Barcode Scanner,1,65.19,89.12,2-Power,,5.711045e+12,
3,1K2CF,,Battery,Laptop,Lithium polymer,Main Battery Pack 15.2V 3941mAh,0,151.63,181.95,2-Power,,5.704175e+12,M033W
4,207576-201,,Peripheral,Headphones,Unknown,Blackwire C5220 Stereo USB-A + 3.5mm,3,57.91,69.50,2-Power,,1.722917e+10,
5,207577-201,,Peripheral,Headphones,Unknown,"Blackwire 5210, Mono, USB-A Headset",10,51.70,62.05,2-Power,,5.704174e+12,
6,209749-201,,Peripheral,Headphones,Unknown,"Blackwire 3220 Stereo, USB-C Headset",0,24.03,33.39,2-Power,,1.722917e+10,

In [9]:
df1['Brand'].unique()

array(['2-Power', 'AcBel', 'Acer', 'Asus', 'Brother', 'Canon', 'Chicony',
       'Compaq', 'Dell', 'Delta', 'Duracell', 'Energizer', 'Fujitsu',
       'Fujitsu Siemens', 'HP', 'Kyocera', 'Lenovo', 'Lexmark', 'Maxell',
       'Microsoft', 'Panasonic', 'Poly', 'Saft', 'Samsung', 'Seagate',
       'Sony', 'Toshiba', 'Varta', 'Xerox', 'Yuasa', 'Zebra'],
      dtype=object)

In [10]:
df1 = df1[['Part_number','Type','Brand', 'Description','Stock_level', 'Price_EUR']]

In [11]:
old_names = ['Part_number','Type' ,'Brand', 'Description','Stock_level', 'Price_EUR']
columns_rename=['Ref_produit','Categorie','Marque','Description','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df1  = df1.rename(columns=rename_dict)
df1.head(3)

,Ref_produit,Categorie,Marque,Description,Quantite,Prix
0,00PA474,Laptop,2-Power,Backlit Keyboard (Portuguese),1,40.78
1,00PA556,Laptop,2-Power,Backlit Keyboard (Portuguese),1,40.78
2,1200G-2USB-1,Peripheral,2-Power,Voyager 1200g Barcode Scanner,1,65.19

In [12]:
commun_columns=['Ref_produit', 'Marque', 'Description']
df0 = pd.concat([df1[commun_columns], DGFTECH[commun_columns]])

In [13]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23134 entries, 0 to 10177
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Ref_produit  23134 non-null  object
 1   Marque       23134 non-null  object
 2   Description  23134 non-null  object
dtypes: object(3)
memory usage: 722.9+ KB

In [14]:
file_path =r"/kaggle/input/stp-dataset/2DEVEA_pca_cat.csv"

# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df2 = pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df2' in locals():
    print(df2.info())
else:
    print("Failed to load the file with the provided encodings.")

Error with utf-8 encoding: 'utf-8' codec can't decode byte 0xe9 in position 1200: invalid continuation byte
File successfully loaded with ISO-8859-1 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10033 entries, 0 to 10032
Data columns (total 13 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   CodeArticleWeb                        10033 non-null  object
 1   CodeArticle                           10033 non-null  object
 2   RefFournisseur                        10033 non-null  object
 3   GenCode                               9988 non-null   object
 4   Designation_Longue                    10033 non-null  object
 5   Groupe                                10032 non-null  object
 6   Marque                                10033 non-null  object
 7   Stock                                 10033 non-null  int64
 8   PrixHT_sans_ecop_et_sans_sorecop      10033 non-null  float64
 9   Ecopart_HT                            10033 non-null  float64
 10  Sorecop_HT                            10033 non-null  float64
 11  PrixHT_comprenant_Ecopart_et_Sorecop  10033 non-null  float64
 12  PrixPublic_HT                         10033 non-null  float64
dtypes: float64(5), int64(1), object(7)
memory usage: 1019.1+ KB
None

In [15]:
df2= df2[['CodeArticle','Groupe','Marque', 'Designation_Longue','RefFournisseur','Stock', 'PrixPublic_HT']]
old_names = ['CodeArticle','Groupe','Marque', 'Designation_Longue','RefFournisseur','Stock', 'PrixPublic_HT ']
columns_rename=['Ref_produit','Categorie','Marque','Description','Ref_fournisseur','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df2  = df2.rename(columns=rename_dict)
df2.head(3)

,Ref_produit,Categorie,Marque,Description,Ref_fournisseur,Quantite,PrixPublic_HT
0,0-32LS03CBU,TELEVISION,SAMSUNG,TV SAMSUNG The Frame 32'' 2023 TQ32LS03CBUXXC,TQ32LS03CBUXXC,12,0.0
1,0-55LST7TCU,TELEVISION,SAMSUNG,TV SAMSUNG 55 THE TERRACE QLED 4K SMART TV EXT...,QE55LST7TCUXXC,2,0.0
2,0-65LST7TCU,TELEVISION,SAMSUNG,TV SAMSUNG 65 THE TERRACE QLED 4K SMART TV EXT...,QE65LST7TCUXXC,1,0.0

In [16]:
file_path = r"/kaggle/input/stp-dataset/Arles (1).csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df3 = pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df3' in locals():
    print(df3.info())
else:
    print("Failed to load the file with the provided encodings.")

File successfully loaded with utf-8 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1767 entries, 0 to 1766
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Describtion  1767 non-null   object
 1   manufactur   1767 non-null   object
 2   EDP          1767 non-null   object
 3   QTY          1767 non-null   int64
 4   Price        1767 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 69.1+ KB
None

In [17]:
df3.head(3)

,Describtion,manufactur,EDP,QTY,Price
0,Development Unit Ricoh D8093002 cyan,RICOH,D8093002,2,0.00
1,Development Unit Ricoh D8093004 yellow,RICOH,D8093004,7,0.00
2,KYOCERA-MITA Toner (TK580C) (PUx15) (QR code),KYOCERA MITA,TK-580C,17,64.35

In [18]:
len(df3['EDP'].unique())

1766

In [19]:
df3= df3[['EDP', 'Describtion','manufactur','QTY', 'Price']]
old_names = ['EDP', 'Describtion','manufactur','QTY', 'Price']
columns_rename=['Ref_produit','Description','Ref_fournisseur','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df3  = df3.rename(columns=rename_dict)
df3.head(3)

,Ref_produit,Description,Ref_fournisseur,Quantite,Prix
0,D8093002,Development Unit Ricoh D8093002 cyan,RICOH,2,0.00
1,D8093004,Development Unit Ricoh D8093004 yellow,RICOH,7,0.00
2,TK-580C,KYOCERA-MITA Toner (TK580C) (PUx15) (QR code),KYOCERA MITA,17,64.35

In [20]:
import pandas as pd

file_path =r"/kaggle/input/stp-dataset/Copaco.csv"
df4= pd.read_csv(file_path)
print(df4.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43832 entries, 0 to 43831
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Artikel               43832 non-null  object
 1   Fabrikantscode        43832 non-null  object
 2   Merk                  43832 non-null  object
 3   Omschrijving          43832 non-null  object
 4   Prijs                 43832 non-null  float64
 5   Prijs_incl_heffingen  43832 non-null  float64
 6   Voorraad              43832 non-null  int64
 7   produktindeling       43832 non-null  object
 8   UNSPSC_code           43832 non-null  int64
 9   EAN_code              25259 non-null  object
 10  status                43832 non-null  int64
 11  Auvibel               43832 non-null  float64
 12  Reprobel              43832 non-null  float64
 13  Recupel               43832 non-null  float64
 14  Bebat                 43832 non-null  float64
 15  Datum aanmaken:       0 non-null      float64
 16  07-17-2024            0 non-null      float64
dtypes: float64(8), int64(3), object(6)
memory usage: 5.7+ MB
None

In [21]:
df4.head(3)

,Artikel,Fabrikantscode,Merk,Omschrijving,Prijs,Prijs_incl_heffingen,Voorraad,produktindeling,UNSPSC_code,EAN_code,status,Auvibel,Reprobel,Recupel,Bebat,Datum aanmaken:,07-17-2024
0,ACR-DP.PR2EE.X67,DP.PR2EE.X67,Acer,Acer USB Keyboard - BE. Azerty - Black,20.65,20.77,0,ACRNOT---ASP,43211503,4712842943662,0,0.0,0.0,0.12,0.0,NaN,NaN
1,ACR-DP.PR2EE.X71,DP.PR2EE.X71,Acer,Keyboard Pro2 USB Black QWERTY US International,13.37,13.49,100,ACRP-C---ASP,43000000,4712842943648,2,0.0,0.0,0.12,0.0,NaN,NaN
2,ACR-DP.Z35WW.P01,DP.Z35WW.P01,Acer,Predator BiFrost Intel ARC A750 OC - APBF-IA75...,245.00,245.00,5,ACRNOT---ASP,43211503,4711121619083,0,0.0,0.0,0.00,0.0,NaN,NaN

In [22]:
df4= df4[['Artikel','produktindeling','Merk','Omschrijving','Fabrikantscode','Voorraad', 'Prijs']]
old_names = ['Artikel','produktindeling','Merk','Omschrijving','Fabrikantscode','Voorraad', 'Prijs']
columns_rename=['Ref_produit','Categorie','Marque','Description','Ref_fournisseur','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df4  = df4.rename(columns=rename_dict)
df4.head(3)

,Ref_produit,Categorie,Marque,Description,Ref_fournisseur,Quantite,Prix
0,ACR-DP.PR2EE.X67,ACRNOT---ASP,Acer,Acer USB Keyboard - BE. Azerty - Black,DP.PR2EE.X67,0,20.65
1,ACR-DP.PR2EE.X71,ACRP-C---ASP,Acer,Keyboard Pro2 USB Black QWERTY US International,DP.PR2EE.X71,100,13.37
2,ACR-DP.Z35WW.P01,ACRNOT---ASP,Acer,Predator BiFrost Intel ARC A750 OC - APBF-IA75...,DP.Z35WW.P01,5,245.00

In [23]:
file_path = r"/kaggle/input/stp-dataset/DIFOX-24607888 (1).csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df5 = pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df5' in locals():
    print(df5.info())
else:
    print("Failed to load the file with the provided encodings.")

File successfully loaded with utf-8 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36833 entries, 0 to 36832
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Catégorie                 36833 non-null  object
 1   Désignation catégorie     36833 non-null  object
 2   N° d'article              36833 non-null  int64
 3   Désignation de l'article  36833 non-null  object
 4   Nom du fournisseur        36833 non-null  object
 5   N° d'art. du fournisseur  36520 non-null  object
 6   Code barre 1              36267 non-null  float64
 7   Code barre 2              1172 non-null   float64
 8   Code barre 3              100 non-null    float64
 9   Code barre 4              26 non-null     float64
 10  Code barre 5              13 non-null     float64
 11  Code barre 6              9 non-null      float64
 12  Prix de vente             36833 non-null  float64
 13  Disponibilité (step)      36767 non-null  object
 14  Nouveautés                19 non-null     float64
 15  Changements de prix       336 non-null    object
 16  Fins de référencement     66 non-null     float64
 17  Sonderversandkosten       36833 non-null  int64
 18  Gurtmass                  36833 non-null  int64
dtypes: float64(9), int64(3), object(7)
memory usage: 5.3+ MB
None

In [24]:
df5['Nom du fournisseur'].unique()

array(['keine Marke', 'Fujifilm', 'Kidywolf', 'AgfaPhoto', 'Ilford',
       'Harman', 'Easypix', 'Kodak', 'Pentax', 'Sony', 'VTech', 'Rollei',
       'Ricoh', 'Canon', 'Denver', 'Sealife', 'Panasonic', 'Olympus',
       'Minox', 'Braun Phototechnik', 'Bushnell', 'Enlaps', 'Samyang',
       'OM System', 'Sekonic', 'Gossen', 'Novoflex', 'Kaiser Fototechnik',
       'Godox', 'walimex', 'Nikon', 'Blackmagic Design', 'Reflecta',
       'Hama', 'Walther', 'Deknudt', 'Nielsen Design', 'ZEP', 'Goldbuch',
       'Zilverstad', 'Daiber', 'Durable', 'Mitsubishi Electric', 'DNP',
       'Epson', 'Umax-HiTi', 'OEM für Citizen', 'Insta360', 'Kandao',
       'Transcend', 'Garmin', 'Chasing Innovation', 'Logitech', 'RGBLink',
       'IPEVO', 'LG', 'Samsung', 'Hisense', 'Sharp', 'Grundig', 'Lenco',
       'BENQ', 'InFocus', 'Acer', 'Xgimi', 'Philips', 'Hewlett Packard',
       'Screenplay', 'Kindle', 'Google', 'Apple', 'Strong', 'Imperial',
       'Sangean', 'TechniSat', 'Kenwood', 'Albrecht', 'Pure', 'Telestar',
       'Teac', 'Denon', 'Pioneer', 'Audio Technica', 'JVC', 'Marshall',
       'Bose', 'Klipsch', 'Rode', 'Deity', 'Joby', 'OWL Labs',
       'König & Meyer', 'In - Akustik', 'OneforAll', 'Sennheiser',
       'Marmitek', 'Turtle Beach', 'Koss', 'UGREEN', 'TomTom', 'Midland',
       'Fantec', 'Belkin', 'OneOdio', 'Boompods', 'Jabra', 'Beats',
       'DIGITUS', 'ednet', 'Plantronics', 'Razer', 'Lenovo',
       'CONCEPTRONIC', 'Roccat', 'Rapoo', 'AOC', 'Asus', 'MadCatz',
       'HyperX', 'Xiaomi', 'Suunto', 'JLab', 'Magnat', 'Ultimate Ears',
       'Dockin', 'Native Union', 'Microsoft', 'Amazon Echo', 'Omnitronic',
       'ECS IPC', 'Nintendo', 'Millennium 2000', 'Arcade', 'ready2gaming',
       'PDP', 'Thrustmaster', 'Thermaltake', 'be quiet!', 'LC Power',
       'PocketBook', 'Tolino', 'Xoro', 'Nokia', 'Vogels', 'Fellowes',
       'Xlayer', '3M', 'PanzerGlass', 'Wacom', 'Lamy', 'Dell',
       'BlueWalker', 'Cyberpower', 'APC by Schneider Electric', 'Iiyama',
       'Fujitsu', 'MSI', 'Verbatim', 'Plustek', 'Microtek', 'Avision',
       'Kyocera', 'Brother', 'Dymo', 'Clean Office', 'KeySonic',
       'Evoluent', 'Cherry', 'Corsair', 'Toucan', 'Electronic Arts',
       'Elinchrom', 'RaidSonic', 'SanDisk', 'Wise', 'AMD', 'Intel',
       'Rivacase', 'Brennenstuhl', 'Crucial', 'DATACOLOR', 'Level One',
       'TP-Link', 'Zyxel', 'Netgear', 'D-Link', 'Ubiquiti', 'AVM',
       'Starlink', 'Freecom', 'Timekettle', 'Casio', 'Gigaset', 'Doro',
       'Grandstream', 'KMP', 'Motorola', 'OLYMPIA', 'Emporia', 'Beafon',
       'AGM MOBILE', 'Nothing Phone', 'ZTE', 'realme', 'CAT', 'Fairphone',
       'Crosscall', 'Nomad', 'Woodcessories', 'Decoded', 'GIGA Fixxoo',
       'iFixit', 'Medisana', 'Polar', 'Amazfit', 'HUAWEI',
       'One Button Phone', 'Pitaka', 'DeLonghi', 'Unold', 'Graef',
       'Cloer', 'Russell Hobbs', 'Braun', 'Bosch', 'ProfiCook', 'Sage',
       'Steba', 'Bomann', 'Moulinex', 'Ariete', 'Severin', 'Caso',
       'Stelton', 'Makita', 'Gastroback', 'Clatronic', 'KitchenAid',
       'Ninja', 'Solis', 'Zwilling', 'WMF', 'Ritter', 'Berkel',
       'Zassenhaus', 'Beurer', 'Soehnle', 'Joseph Joseph', 'Ooni',
       'TFA-Dostmann', 'nutribullet', 'Dualit', 'Rommelsbacher', 'Krups',
       'Melitta', 'Rowenta', 'Gaggia', 'Rocket Espresso Milano',
       'Siemens', 'Acopino', 'Alessi', 'Leopold Vienna', 'EUREKA',
       'Didiesse', 'Grimac', 'Bialetti', 'Joerges',
       'Torrefazione Caffè Pabios di Petralli', 'Tefal', 'Gorenje',
       'G3Ferrari', 'Weber', 'Campingaz', 'Ankarsrum', 'Gefu', 'Weck',
       'Princess', 'Levenhuk', 'OTOTO', 'Oral-B', 'Remington', 'SANITAS',
       'Revlon', 'ProfiCare', 'Dyson', 'Shark', 'Dreame', 'Technoline',
       'Bresser', 'Mebus', 'Brita', 'BWT', 'Aarke', 'SodaStream', 'Aqvia',
       'Govee', 'Mobicool', 'EcoFlow', 'Coleman', 'Singer', 'Gritzner',
       'Kärcher', 'Nilfisk', 'AEG', 'Tineco', 'Trifo', 'ECOVACS',
       'Black & Decker', 'Leifheit', 'Stadler Form', 'Bauknecht',
       'Papirho', 'Zipper', 'SpeedComfort', 'Haier', 'BEKO', 'Saeco',
       'Swirl', 'Menalux', 'Metabo', 'Brabantia', 'Krinner', 'Ansmann',
       'Varta', 'GP Batteries', 'Energizer', 'Duracell', 'Eneloop',
       'Anker', 'Hedbox', 'REV', 'Intenso', 'Century', 'Ember', 'Atomos',
       'Ryobi', 'DeWalt', 'Milwaukee', 'Einhell', 'Gardena', 'Fein',
       'EasyCover', 'Cullmann', 'Wenger', 'Dicota', 'B&W International',
       'Lowepro', 'Vanguard', 'mantona', 'Pacsafe', 'B+W', 'Shape',
       'OP Tech', 'Fidlock', 'STMNT', 'Speck', 'Spigen', 'Dörr', 'KNIPEX',
       'Fiskars', 'Stanley Black&Decker', 'Wera', 'Wiha', 'SoFlow',
       'Herma', 'Holzmann', 'Raynox', 'Tether Tools', 'Falcon', 'PGYTECH',
       'PocketWizard', 'Stealth Gear', 'Buteo Photo Gear', 'POLARPRO',
       'Visible Dust', 'Green Clean', 'Camgloss', 'Kinetronics',
       'Carson Optical', 'Zhiyun', 'Discovery', 'Kipon', 'Slik', 'Velbon',
       'Sachtler', 'Aputure', 'Nanlite', 'Amaran', 'Osram',
       'Orangemonkie', 'Elmo', 'equip', 'August', 'Ikan', 'Desview',
       'Portkeys', 'Texas Instruments', 'Parker', 'Sharpie', 'Rotring',
       'Paper Mate', 'Tesa', 'Inapa', 'Hahnemühle', 'tecno',
       'Mondi Color Copy', 'Silverlab', 'Polaroid', 'Lexmark', 'DJI',
       'Scosche', 'Walkstool', 'Original Wolfen', 'Western Digital',
       'LaCie', 'Seagate', 'Toshiba', 'ADATA', 'Kioxia', 'Kingston',
       'Goodram', 'Angelbird', 'Micron', 'MyMedia', 'Univers', 'Carrera',
       'Dickie', 'LEGO', 'Schleich', 'ELMER´S', 'Ravensburger', 'Revell',
       'Jada', 'Xplora', 'Trousselier', 'Amewi', 'Game Factory',
       'Ambassador', 'Creagami', 'Theo Klein', 'Smoby', 'BIG', 'Steinel',
       'WORX', 'Vileda', 'Xavax', 'Felco', 'Opinel', 'Gerber',
       'Alpen Swiss Tools', 'Silky', 'LotusGrill', 'Alfa Forni', 'ZiiPa',
       'Looft', 'Laguiole', 'Leica', 'Ermenrich', 'BMI', 'KS Tools',
       'Gedore', 'Brilliant Tools', 'NWS', 'BESSEY', 'NOVUS',
       'Brockhaus Heuer', 'Picard', 'Halder', 'Kirschen', 'Leatherman',
       'Uvex', 'Aerotec', 'Odys', 'Perfectpro', 'Pica-Marker',
       'Alpen-Maykestag', 'Fischer', 'Klingspor', 'DieMaus', 'NewGarden',
       '8seasons', 'Wofi Leuchten', 'ab+', 'Piffany Copenhagen',
       'Broggi Design', 'Sompex', 'XCell', 'Fenix', 'Ledlenser', 'HyCell',
       'Maglite', 'LinkDesk', 'Switchbot', 'Ring', 'Meross',
       'Lite Bulb Moments', 'Bold', 'Masterlock', 'Abus',
       'Ei Electronics', 'Wallbox', 'NRGkick', 'Webasto', 'Easee',
       'Jackery', 'Hyrican', 'Bluetti', 'Technaxx', 'Grohe', 'Hansgrohe',
       'Ninebot', 'Victorinox', 'Morakniv', 'Katadyn', 'Tacx', 'Sevylor',
       'Danubia', 'National Geographic', 'Noblex', 'Staub', 'Le Creuset',
       'De Buyer', 'Lagostina', 'Fissler', 'Stanley', 'Ballarini', 'Güde',
       'KAI', 'Miyabi', 'Yaxell', 'Global', 'Dick', 'Grattoni', 'Marcato',
       'Imperia', 'Emsa', 'KAISER', 'Rösle', 'Bredemeijer', 'Sambonet',
       'L oca nera', 'Coravin', 'Peugeot', 'Mepal', 'Sigg', 'Chillys',
       'Asobu', 'Bodum', 'Wesco', 'Secolan', 'Ibena', 'Bugatti',
       'Rig-Tig', 'PETKIT', 'TensCare', 'heat it'], dtype=object)

In [25]:
df5= df5[["N° d'art. du fournisseur","Désignation catégorie","Désignation de l'article","Nom du fournisseur","Disponibilité (step)","Prix de vente"]]
old_names = ["N° d'art. du fournisseur","Désignation catégorie","Désignation de l'article","Nom du fournisseur","Disponibilité (step)","Prix de vente"]
columns_rename=['Ref_produit','Categorie','Description','Marque','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df5  = df5.rename(columns=rename_dict)
df5.head(3)

,Ref_produit,Categorie,Description,Marque,Quantite,Prix
0,FPP36SUBW,Travaux photo N&B,Développement complet SUC N&B app. photo jetable,keine Marke,> 20,17.96
1,FPP36SW,Travaux photo N&B,Développement complet film petit format 35mm N&B,keine Marke,> 10,17.96
2,FPPSB,Travaux photo N&B,Développement film + Scan N&B Film pet. format...,keine Marke,5,11.45

In [26]:
file_path =r"/kaggle/input/stp-dataset/EET_DGF (1).csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df6 = pd.read_csv(file_path, encoding=encoding, sep='\t', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df6' in locals():
    print(df6.info())
else:
    print("Failed to load the file with the provided encodings.")

Error with utf-8 encoding: 'utf-8' codec can't decode byte 0xe2 in position 246: invalid continuation byte
File successfully loaded with ISO-8859-1 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1183781 entries, 0 to 1183780
Data columns (total 12 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   Brand Name               1183781 non-null  object
 1   Item No.                 1183781 non-null  object
 2   Manufacturer Part No     1183781 non-null  object
 3   OEM Part Number          252032 non-null   object
 4   Description              1183731 non-null  object
 5   Description 2            538098 non-null   object
 6   Home stock               1183781 non-null  object
 7   Customers Price          1183778 non-null  object
 8   EAN/UPC                  351340 non-null   object
 9   Web Category Name        1183658 non-null  object
 10  Web Category Tree        1183658 non-null  object
 11  Item Product Link (Web)  1183778 non-null  object
dtypes: object(12)
memory usage: 108.4+ MB
None

In [27]:
df6.head()

,Brand Name,Item No.,Manufacturer Part No,OEM Part Number,Description,Description 2,Home stock,Customers Price,EAN/UPC,Web Category Name,Web Category Tree,Item Product Link (Web)
0,Lenovo,00HV340,00HV340,NaN,RDN PDB to HDD BP power cabl,NaN,"0,00","27,00",NaN,Câbles SATA,"Pièces pour serveur, notebook & imprimante>Câb...",https://www.eetgroup.com/fr-fr/itemId?itemid=0...
1,Dell,00HV6,00HV6,NaN,Dvd Super-Multi Drive,NaN,"0,00","79,20",5704174278887,Autres pièces de rechange pour notebook,"Pièces pour serveur, notebook & imprimante>Not...",https://www.eetgroup.com/fr-fr/itemId?itemid=0...
2,Lenovo,00HV799,00HV799,NaN,PDB to MB for CPU ODD Power ca,NaN,"0,00","30,90",NaN,Autre,"Pièces pour serveur, notebook & imprimante>Autre>",https://www.eetgroup.com/fr-fr/itemId?itemid=0...
3,Lenovo,00HW000-RFB,00HW000-RFB,NaN,BATTERY 4C,**Refurbished**,"0,00","164,70",NaN,Autre,"Pièces pour serveur, notebook & imprimante>Autre>",https://www.eetgroup.com/fr-fr/itemId?itemid=0...
4,Lenovo,00HW001-RFB,00HW001-RFB,NaN,BATTERY 4C YOGA 14 LI-ION,**Refurbished**,"0,00","112,80",5711783852506,Batteries,"Pièces pour serveur, notebook & imprimante>Not...",https://www.eetgroup.com/fr-fr/itemId?itemid=0...

In [28]:
df6= df6[["Item No.","Web Category Tree",'Brand Name',"Description",'Home stock', 'Customers Price']]
old_names = ["Item No.","Web Category Tree",'Brand Name',"Description",'Home stock', 'Customers Price']
columns_rename=['Ref_produit','Categorie','Marque','Description','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df6  = df6.rename(columns=rename_dict)
df6.head(3)

,Ref_produit,Categorie,Marque,Description,Quantite,Prix
0,00HV340,"Pièces pour serveur, notebook & imprimante>Câb...",Lenovo,RDN PDB to HDD BP power cabl,"0,00","27,00"
1,00HV6,"Pièces pour serveur, notebook & imprimante>Not...",Dell,Dvd Super-Multi Drive,"0,00","79,20"
2,00HV799,"Pièces pour serveur, notebook & imprimante>Autre>",Lenovo,PDB to MB for CPU ODD Power ca,"0,00","30,90"

In [29]:
df6.describe()

,Ref_produit,Categorie,Marque,Description,Quantite,Prix
count,1183781,1183658,1183781,1183731,1183781,1183778
unique,1183781,627,431,711836,932,46922
top,00HV340,"Pièces pour serveur, notebook & imprimante>Autre>",Lenovo,BDPLANAR,"0,00","11,10"
freq,1,706189,212823,3748,1153411,12881

In [30]:
file_path=r"/kaggle/input/stp-dataset/FlexIT (1).csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df7= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df7' in locals():
    print(df7.info())
else:
    print("Failed to load the file with the provided encodings.")

File successfully loaded with utf-8 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799 entries, 0 to 798
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Manufacturer              797 non-null    object
 1   Manufacturer Part Number  799 non-null    object
 2   Flex IT Part Number       799 non-null    object
 3   Description               799 non-null    object
 4   Stock Quantity            799 non-null    int64
 5   Sales Price               799 non-null    float64
 6   SRP                       799 non-null    float64
 7   Status                    799 non-null    object
 8   Alias                     799 non-null    object
 9   Incoming Quantity         799 non-null    int64
 10  Incoming Date             4 non-null      object
 11  Status Description        799 non-null    object
 12  Category                  799 non-null    object
 13  Product Group             799 non-null    object
 14  IceCat ID                 4 non-null      float64
 15  Length                    750 non-null    float64
 16  Width                     750 non-null    float64
 17  Height                    748 non-null    float64
 18  Cubage                    748 non-null    float64
 19  Weight                    794 non-null    float64
 20  EAN                       52 non-null     float64
 21  Item number no status     799 non-null    int64
dtypes: float64(9), int64(3), object(10)
memory usage: 137.5+ KB
None

In [31]:
df7= df7[["Manufacturer Part Number","Category",'Manufacturer',"Description",'Stock Quantity', 'SRP']]
old_names = ["Manufacturer Part Number","Category",'Manufacturer',"Description","Fournisseur",'Stock Quantity', 'SRP']
columns_rename=['Ref_produit','Categorie','Marque','Description','Fournisseur','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df7 = df7.rename(columns=rename_dict)
df7['Fournisseur'] = 'Flex IT'
df7.head(3)

,Ref_produit,Categorie,Marque,Description,Quantite,Prix,Fournisseur
0,409H3B/A-AS,Mobile Phones/Handhelds,APPLE,Apple Watch Series 6 44mm LTE Graphite SS Stai...,212,219.0,Flex IT
1,4G2D3B/A-AS,Mobile Phones/Handhelds,APPLE,Apple Watch Series 6 44mm LTE Gold ALU Aluminu...,34,189.0,Flex IT
2,4G2E3B/A-AS,Mobile Phones/Handhelds,APPLE,Apple Watch Series 6 44mm LTE Space Gray ALU A...,1,189.0,Flex IT

In [32]:
file_path=r"/kaggle/input/stp-dataset/Supplies24_30062023.csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df8= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df8' in locals():
    print(df8.info())
else:
    print("Failed to load the file with the provided encodings.")

Error with utf-8 encoding: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
File successfully loaded with ISO-8859-1 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8235 entries, 0 to 8234
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Rfrence             8235 non-null   object
 1   Prix                  8235 non-null   object
 2   Qty                   8235 non-null   int64
 3   Artikel Beschreibung  8235 non-null   object
dtypes: int64(1), object(3)
memory usage: 257.5+ KB
None

In [33]:
def clean_price(price):
    if isinstance(price, str):
        # Remplacer les virgules par des points et enlever les ?
        price = price.replace(',', '.').replace('?', '')
    try:
        return float(price)
    except ValueError:
        return None

# Appliquer la fonction à la colonne 'Prix'
df8['Prix'] = df8['Prix'].apply(clean_price)

In [34]:
df8= df8[["Rfrence","Artikel Beschreibung",'Qty', 'Prix']]
old_names = ["Rfrence","Artikel Beschreibung",'Qty', 'Prix']
columns_rename=['Ref_produit','Description','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df8 = df8.rename(columns=rename_dict)
df8.head(3)

,Ref_produit,Description,Quantite,Prix
0,AP18020A6,ORIGINAL Agfa Photo Papier Blanc AP18020A6 Le ...,1,0.53
1,APB1000SETD,ORIGINAL Agfa Photo Multipack Noir(e) / Cyan /...,1,6.86
2,APB1100BD,ORIGINAL Agfa Photo Cartouche d'encre Noir(e) ...,0,2.66

In [35]:
# Extraction du premier mot de la description pour la colonne "Marque"
df8['Marque'] = df8['Description'].apply(lambda x: x.split()[1] if pd.notna(x) else 'Inconnu')
df8

,Ref_produit,Description,Quantite,Prix,Marque
0,AP18020A6,ORIGINAL Agfa Photo Papier Blanc AP18020A6 Le ...,1,0.53,Agfa
1,APB1000SETD,ORIGINAL Agfa Photo Multipack Noir(e) / Cyan /...,1,6.86,Agfa
2,APB1100BD,ORIGINAL Agfa Photo Cartouche d'encre Noir(e) ...,0,2.66,Agfa
3,APB1100SETD,ORIGINAL Agfa Photo Multipack Noir(e) / Cyan /...,0,7.49,Agfa
4,APB123BD,ORIGINAL Agfa Photo Cartouche d'encre Noir(e) ...,1,3.67,Agfa
...,...,...,...,...,...
8230,800263-205 12PCK,ORIGINAL Zebra Etiquettes 800263-205 12PCK Z-S...,1,149.19,Zebra
8231,800284-605,ORIGINAL Zebra Etiquettes 800284-605 Z-Perform,1,160.36,Zebra
8232,87000,ORIGINAL Zebra Etiquettes 87000 Z-Select Pack ...,1,66.25,Zebra
8233,GK42-202220-000,ORIGINAL Zebra Imprimante GK42-202220-000 GK420d,1,348.37,Zebra
8234,GK42-202520-000,ORIGINAL Zebra Imprimante GK42-202520-000 GK420d,1,248.84,Zebra

In [36]:
df8['Marque'].unique()

array(['Agfa', 'AVERY', 'Brother', 'Canon', 'Colop', 'Dell', 'Develop',
       'Diverse', 'DYMO', 'Epson', 'Fujitsu', 'Honeywell', 'HP', 'Jabra',
       'Konica', 'Kyocera', 'Lenovo', 'Lexmark', 'Logitech', 'Mita',
       'Mitsubishi', 'MyClean', 'Nashuatec', 'NewStar', 'NRG', 'OKI',
       'Olivetti', 'Panasonic', 'Peach', 'Plustek', 'Prindo', 'Quantum',
       'Ricoh', 'Riso', 'Samsung', 'Seiko', 'Sharp', 'Sony', 'Summer',
       'Tally', 'Tonex', 'TOP', 'Toshiba', 'Utax', 'V7', 'Xerox', 'Zebra'],
      dtype=object)

In [37]:
file_path=r"/kaggle/input/stp-dataset/TOPUS_STOCKLIST_DGF (2).csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df9= pd.read_csv(file_path, encoding=encoding, sep=',', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df9' in locals():
    print(df9.info())
else:
    print("Failed to load the file with the provided encodings.")

File successfully loaded with utf-8 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4142 entries, 0 to 4141
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sekcja       4142 non-null   object
 1   Part_number  4142 non-null   object
 2   Nazwa        4142 non-null   object
 3   EAN          4142 non-null   object
 4   Stan         4142 non-null   int64
 5   Cena         4142 non-null   object
 6   Waluta       4142 non-null   object
dtypes: int64(1), object(6)
memory usage: 226.6+ KB
None

In [38]:
new_column_names = ['Section',      
    'Part_number',  
   'description' ,       
   'EAN'    ,     
   'stock'   ,      
   'Prix'  ,       
   'Devise']
if len(df9.columns) == len(new_column_names):
                df9.columns = new_column_names
df9.columns

Index(['Section', 'Part_number', 'description', 'EAN', 'stock', 'Prix',
       'Devise'],
      dtype='object')

In [39]:
# Appliquer la fonction à la colonne 'Prix'
df9['Prix'] = df9['Prix'].apply(clean_price)

In [40]:
df9= df9[["Part_number","Section","description",'stock','Prix']]
old_names = ["Part_number","Section","description",'stock','Prix']
columns_rename=['Ref_produit','Categorie','Description','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df9= df9.rename(columns=rename_dict)
df9.head(3)

  Ref_produit         Categorie                 Description  Quantite  Prix
0      TN2000  Brother Supplies  Brother Toner Black TN2000         0  52.5
1      TN2220  Brother Supplies  Brother Toner Black TN2220         0  49.7
2      TN6600  Brother Supplies  Brother Toner Black TN6600        23  38.9

In [41]:
# Extraction du premier mot de la Categorie pour la colonne "Marque"
df9['Marque'] = df9['Categorie'].apply(lambda x: x.split()[0] if pd.notna(x) else 'Inconnu')

In [42]:
df9

,Ref_produit,Categorie,Description,Quantite,Prix,Marque
0,TN2000,Brother Supplies,Brother Toner Black TN2000,0,52.5,Brother
1,TN2220,Brother Supplies,Brother Toner Black TN2220,0,49.7,Brother
2,TN6600,Brother Supplies,Brother Toner Black TN6600,23,38.9,Brother
3,TN3480,Brother Supplies,Brother Toner Black TN3480,100,96.3,Brother
4,DR6000,Brother Supplies,Brother Drum Black DR6000,4,59.9,Brother
...,...,...,...,...,...,...
4137,116R00036,Xerox Supplies,VersaLink B625 Transfer Roller 116R00036,0,23.7,Xerox
4138,116R00037,Xerox Supplies,VersaLink B625 Bypass Tray Roller Kit 116R00037,0,25.2,Xerox
4139,116R00035,Xerox Supplies,VersaLink B625 Paper Feed Roller Kit 116R00035,0,25.2,Xerox
4140,115R00161,Xerox Supplies,VersaLink B620 Fuser 220 V 115R00161,0,332.5,Xerox
4141,108R01471,Xerox Supplies,Phaser 3330 WC 33xx Tray 2 Feed Roll 108R01471,0,27.3,Xerox

In [43]:
file_path=r"/kaggle/input/stp-dataset/argor10072024 (1).csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df10= pd.read_csv(file_path, encoding=encoding, sep=',', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df10' in locals():
    print(df10.info())
else:
    print("Failed to load the file with the provided encodings.")

File successfully loaded with utf-8 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  564 non-null    float64
 1   Unnamed: 1  564 non-null    object
 2   Unnamed: 2  564 non-null    object
 3   Unnamed: 3  564 non-null    object
 4   Unnamed: 4  564 non-null    float64
 5   Unnamed: 5  564 non-null    float64
dtypes: float64(3), object(3)
memory usage: 26.6+ KB
None

In [44]:
df10= df10[["Unnamed: 3","Unnamed: 2","Unnamed: 5"]]
old_names = ["Unnamed: 3","Unnamed: 2","Unnamed: 5"]
columns_rename=['Ref_produit','Description','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df10 = df10.rename(columns=rename_dict)
df10.head(3)

  Ref_produit       Description    Prix
0     TN-3512   Brother TN-3512  111.18
1     TN-3520   Brother TN-3520  134.64
2    TN-910 C  Brother TN-910 C  207.06

In [45]:
# Extraction du premier mot de la Categorie pour la colonne "Marque"
df10['Marque'] = df10['Description'].apply(lambda x: x.split()[0] if pd.notna(x) else 'Inconnu')

In [46]:
df10

    Ref_produit       Description    Prix   Marque
0       TN-3512   Brother TN-3512  111.18  Brother
1       TN-3520   Brother TN-3520  134.64  Brother
2      TN-910 C  Brother TN-910 C  207.06  Brother
3      TN-910 M  Brother TN-910 M  207.06  Brother
4      TN-910 Y  Brother TN-910 Y  207.06  Brother
..          ...               ...     ...      ...
560   006R01518   Xerox 006R01518   78.54    Xerox
561   006R01519   Xerox 006R01519   78.54    Xerox
562   106R02310   Xerox 106R02310  103.02    Xerox
563   106R02773   Xerox 106R02773   48.96    Xerox
564         NaN               NaN     NaN  Inconnu

[565 rows x 4 columns]

In [47]:
file_path=r"/kaggle/input/stp-dataset/axro.csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df11= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df11' in locals():
    print(df11.info())
else:
    print("Failed to load the file with the provided encodings.")

Error: No columns to parse from file
Error: No columns to parse from file
Error: No columns to parse from file
Failed to load the file with the provided encodings.

In [48]:
file_path=r"/kaggle/input/stp-dataset/cid_export_04072023.csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df12= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df12' in locals():
    print(df12.info())
else:
    print("Failed to load the file with the provided encodings.")

Error with utf-8 encoding: 'utf-8' codec can't decode byte 0x87 in position 916: invalid start byte
File successfully loaded with ISO-8859-1 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 922 entries, 0 to 921
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Code article             730 non-null    object
 1   Marque                   730 non-null    object
 2   Description commerciale  730 non-null    object
 3    stock                   730 non-null    object
 4    PV HT
? HT              730 non-null    object
 5   Unnamed: 5               0 non-null      float64
 6   Unnamed: 6               0 non-null      float64
 7   Unnamed: 7               0 non-null      float64
 8   Unnamed: 8               0 non-null      float64
 9   Unnamed: 9               0 non-null      float64
 10  Unnamed: 10              0 non-null      float64
 11  Unnamed: 11              0 non-null      float64
 12  Unnamed: 12              0 non-null      float64
 13  Unnamed: 13              0 non-null      float64
 14  Unnamed: 14              0 non-null      float64
 15  Unnamed: 15              0 non-null      float64
 16  Unnamed: 16              0 non-null      float64
 17  Unnamed: 17              0 non-null      float64
 18  Unnamed: 18              0 non-null      float64
 19  Unnamed: 19              0 non-null      float64
dtypes: float64(15), object(5)
memory usage: 144.2+ KB
None

In [49]:
columns_to_drop = ['Unnamed: 5','Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19']
df12 = df12.drop(columns=columns_to_drop)

In [50]:
df12.columns

Index(['Code article', 'Marque', 'Description commerciale', ' stock ',
       ' PV HT\n? HT '],
      dtype='object')

In [51]:
df12= df12[["Code article","Marque","Description commerciale"," stock "," PV HT\n? HT "]]
old_names = ["Code article","Marque","Description commerciale"," stock "," PV HT\n? HT "]
columns_rename=['Ref_produit','Marque','Description','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df12 = df12.rename(columns=rename_dict)
df12.head(3)

,Ref_produit,Marque,Description,Quantite,Prix
0,265A9ET_N,HP,HP 125 Souris filaire USB noir pour HP Z1 G8; ...,662,"5,50 ?"
1,H3T50AA_N,HP,HP X4000B Souris laser sans fil Bluetooth pour...,364,"15,00 ?"
2,L2X04AA_N,HP,HP Adaptateur secteur CA 100-240 V 65 Watt PFC...,260,"9,00 ?"

In [52]:
df12['Prix']=df12['Prix'].apply(clean_price)
df12.head(2)

,Ref_produit,Marque,Description,Quantite,Prix
0,265A9ET_N,HP,HP 125 Souris filaire USB noir pour HP Z1 G8; ...,662,5.5
1,H3T50AA_N,HP,HP X4000B Souris laser sans fil Bluetooth pour...,364,15.0

In [53]:
file_path=r"/kaggle/input/stp-dataset/dexxon (1).csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df13= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df13' in locals():
    print(df13.info())
else:
    print("Failed to load the file with the provided encodings.")

Error with utf-8 encoding: 'utf-8' codec can't decode byte 0xe0 in position 1711: invalid continuation byte
File successfully loaded with ISO-8859-1 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15351 entries, 0 to 15350
Data columns (total 17 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Code article Dexxon                               15351 non-null  object
 1   Code EAN                                          5179 non-null   float64
 2   Description courte de l'article                   15351 non-null  object
 3   PN Constructeur                                   15348 non-null  object
 4   Nom du Fabricant                                  15351 non-null  object
 5   Prix                                              15351 non-null  object
 6   Redevance Sorecop                                 15351 non-null  object
 7   Eco-taxe                                          15351 non-null  object
 8   QtÃ© disponible                                   15351 non-null  int64
 9   UnitÃ© de conditionnement                         15351 non-null  object
 10  Facteur de conversion (par rapport Ã  la piÃ¨ce)  15351 non-null  int64
 11  Poids brut                                        15351 non-null  object
 12  Poids net                                         15351 non-null  object
 13  UnitÃ© de poids                                   15351 non-null  object
 14  HiÃ©rarchie article Niveau 1                      15351 non-null  object
 15  Niveau 2                                          15348 non-null  object
 16  Niveau 3                                          15265 non-null  object
dtypes: float64(1), int64(2), object(14)
memory usage: 2.0+ MB
None

In [54]:
df13.head(3)

,Code article Dexxon,Code EAN,Description courte de l'article,PN Constructeur,Nom du Fabricant,Prix,Redevance Sorecop,Eco-taxe,QtÃ© disponible,UnitÃ© de conditionnement,Facteur de conversion (par rapport Ã la piÃ¨ce),Poids brut,Poids net,UnitÃ© de poids,HiÃ©rarchie article Niveau 1,Niveau 2,Niveau 3
0,000000000000006291,NaN,FM2-5535-000 SHUTTER DRIVE ASSEMBLY,FM2-5535-000,Canon,"49,82","0,00","0,00",0,ST,1,"0,03","0,00",KG,Bureautique,Accessoires,Pieces detachees
1,000000000000006374,NaN,FM4-2531-000 PEDESTAL CONTROLLER PCB ASS,FM4-2531-000,Canon,"29,28","0,00","0,00",0,ST,1,"0,30","0,00",KG,Bureautique,Accessoires,Pieces detachees
2,BFHDD1000LSM,5.060126e+12,Buffalo LinkStation Mini 1TB DLNA White,LS-WS1.0TGL/R1,Buffalo,"149,48","0,00","0,00",5,ST,1,"0,95","0,50",KG,Stockage,HDD et cles USB,HDD

In [55]:
df13= df13[["PN Constructeur","Niveau 2",'Nom du Fabricant',"Description courte de l'article",'QtÃ© disponible', 'Prix']]
old_names = ["PN Constructeur","Niveau 2",'Nom du Fabricant',"Description courte de l'article",'QtÃ© disponible', 'Prix']
columns_rename=['Ref_produit','Categorie','Marque','Description','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df13 = df13.rename(columns=rename_dict)
df13.head(4)

,Ref_produit,Categorie,Marque,Description,Quantite,Prix
0,FM2-5535-000,Accessoires,Canon,FM2-5535-000 SHUTTER DRIVE ASSEMBLY,0,"49,82"
1,FM4-2531-000,Accessoires,Canon,FM4-2531-000 PEDESTAL CONTROLLER PCB ASS,0,"29,28"
2,LS-WS1.0TGL/R1,HDD et cles USB,Buffalo,Buffalo LinkStation Mini 1TB DLNA White,5,"149,48"
3,T4MP-N-P-45,Solutions Services,DS,Bluemega Lecteur de badge universel,0,"139,91"

In [56]:
df13['Fournisseur'] = 'Dexxon'
df13.head()

,Ref_produit,Categorie,Marque,Description,Quantite,Prix,Fournisseur
0,FM2-5535-000,Accessoires,Canon,FM2-5535-000 SHUTTER DRIVE ASSEMBLY,0,"49,82",Dexxon
1,FM4-2531-000,Accessoires,Canon,FM4-2531-000 PEDESTAL CONTROLLER PCB ASS,0,"29,28",Dexxon
2,LS-WS1.0TGL/R1,HDD et cles USB,Buffalo,Buffalo LinkStation Mini 1TB DLNA White,5,"149,48",Dexxon
3,T4MP-N-P-45,Solutions Services,DS,Bluemega Lecteur de badge universel,0,"139,91",Dexxon
4,BAE001,Divers,Brother,Brother Batterie Rechargeable,10,"17,37",Dexxon

In [57]:
file_path=r"/kaggle/input/stp-dataset/eparts.csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df14= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df14' in locals():
    print(df14.info())
else:
    print("Failed to load the file with the provided encodings.")

File successfully loaded with utf-8 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155037 entries, 0 to 155036
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   reference         155037 non-null  object
 1   client-reference  0 non-null       float64
 2   presentation1     155036 non-null  object
 3   presentation2     1070 non-null    object
 4   brand             154799 non-null  object
 5   stock             155037 non-null  int64
 6   client-price      155037 non-null  object
 7   available-date    155036 non-null  object
 8   EAN               621 non-null     object
 9   picture           3604 non-null    object
 10  related-printer   4077 non-null    object
 11  type-produit      4077 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 14.2+ MB
None

In [58]:
df14

,reference,client-reference,presentation1,presentation2,brand,stock,client-price,available-date,EAN,picture,related-printer,type-produit
0,RG5-6533,NaN,YOU CAN ORDER MAINTENANCE KIT C3915,NaN,HPinc,0,"189,00",7-10 days,5705965552711,http://www.eparts.fr/eparts/CustomUpload/374O3...,"LJ 8100, LJ 8150",FUSER UNIT
1,RG5-7061,NaN,FUSER ORIGINAL HP LJ5100,NaN,HPinc,2,"155,00",En stock,5705965639566,http://www.eparts.fr/eparts/CustomUpload/374O3...,LJ 5100,FUSER UNIT
2,RG5-4111,NaN,FUSER UNIT ORIGINAL HP LJ6P,NaN,HPinc,0,"65,00",7-10 days,5712505412664,http://www.eparts.fr/eparts/CustomUpload/374O3...,NaN,NaN
3,RG5-5569,NaN,FUSER LJ2200 NEW HP,NaN,CANON,12,"72,00",En stock,5704327956099,http://www.eparts.fr/eparts/CustomUpload/374O3...,LJ 2200,FUSER UNIT
4,C9153-67908,NaN,FUSER UNIT ORIGINAL HP,NaN,HPinc,0,"405,00",7-10 days,NaN,http://www.eparts.fr/eparts/CustomUpload/374O3...,"LJ 9000, LJ 9050, LJ 9040, LJ M9040, LJ M9050",FUSER UNIT
...,...,...,...,...,...,...,...,...,...,...,...,...
155032,X950X2MG,NaN,TONER X950/X952 (24.000 Sheet) MAGENTO,NaN,KYOCERA,0,"332,48",5-7 days,NaN,NaN,NaN,NaN
155033,X950X2YG,NaN,TONER X950/X952 (24.000 Sheet) YELLOW,NaN,KYOCERA,0,"332,48",5-7 days,NaN,NaN,NaN,NaN
155034,1702MS8NLV-GEN,NaN,MK FS-2100D / FS-2100DN GENERIC,MK-3100,GENERIC,1,"100,00",En stock,NaN,NaN,FS-2100,MAINTENANCE KIT
155035,CF280JC,NaN,TONER CARTRIDGE JUMBO 80X BLACK CONTRACT,10 000 pages,HPinc,0,"89,00",5-7 days,NaN,http://www.eparts.fr/eparts/CustomUpload/374O3...,"LJ M401, LJ M425",CONSUMABLE
155036,CZ129A,NaN,INK CARTRIDGE NO 711,NaN,CET,0,"54,61",5-7 days,NaN,NaN,NaN,NaN

In [59]:
df14= df14[["reference","type-produit",'brand',"presentation1",'stock', 'client-price']]
old_names = ["reference","type-produit",'brand',"presentation1",'stock', 'client-price']
columns_rename=['Ref_produit','Categorie','Marque','Description','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df14 = df14.rename(columns=rename_dict)
df14.head(3)

,Ref_produit,Categorie,Marque,Description,Quantite,Prix
0,RG5-6533,FUSER UNIT,HPinc,YOU CAN ORDER MAINTENANCE KIT C3915,0,"189,00"
1,RG5-7061,FUSER UNIT,HPinc,FUSER ORIGINAL HP LJ5100,2,"155,00"
2,RG5-4111,NaN,HPinc,FUSER UNIT ORIGINAL HP LJ6P,0,"65,00"

In [60]:
file_path=r"/kaggle/input/stp-dataset/imcopex.csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df15= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df15' in locals():
    print(df15.info())
else:
    print("Failed to load the file with the provided encodings.")

File successfully loaded with utf-8 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3407 entries, 0 to 3406
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Manufacturer             3407 non-null   object
 1   OEM No.                  3407 non-null   object
 2   Item group               3407 non-null   object
 3   imcopex Product details  3407 non-null   object
 4   Price                    3407 non-null   object
 5   free stock               3407 non-null   int64
 6   EAN No.                  3271 non-null   float64
 7   Pallet Goods             3407 non-null   int64
 8   Customs Tariff number    1883 non-null   float64
dtypes: float64(2), int64(2), object(5)
memory usage: 239.7+ KB
None

In [61]:
df15

,Manufacturer,OEM No.,Item group,imcopex Product details,Price,free stock,EAN No.,Pallet Goods,Customs Tariff number
0,AMD,100-100000510BOX,CPUs,AMD Ryzen 3 4100 3 8 AMD8 AMD 8 GHz (100-10000...,"49,00",10,7.301433e+11,0,84733080.0
1,AMD,100-100000031BOX,CPUs,AMD Ryzen 5 3600 3 6 AMD6 AMD 6 GHz (100-10000...,"65,72",15,7.301433e+11,0,NaN
2,AMD,100-100001489BOX,CPUs,AMD Ryzen 5 5500GT 3 6 AMD6 AMD 6 GHz (100-100...,"87,69",69,7.301433e+11,0,84733020.0
3,AMD,100-100001488BOX,CPUs,AMD Ryzen 5 5600GT 3 6 AMD6 AMD 6 GHz (100-100...,"108,46",20,7.301433e+11,0,84733020.0
4,AMD,100-100000065BOX,CPUs,AMD Ryzen 5 5600X 3 7 AMD7 AMD 7 GHz (100-1000...,"104,29",47,7.301433e+11,0,84733080.0
...,...,...,...,...,...,...,...,...,...
3402,Zwilling,71030-000-0,Household & Garden,Zwilling Flow Saucepan-Set SaucepanSet 5pcs st...,"106,90",29,4.009840e+12,0,NaN
3403,Zwilling,66460-000-0,Household & Garden,Zwilling Vitality Saucepan-Set SaucepanSet 5pc...,"108,90",20,4.009839e+12,0,NaN
3404,Zyxel,GS2220-28HP-EU0101F,Network Equipment,ZyXEL Switch GS2220-28HP-EU0101F GS222028HPEU0...,"435,42",2,4.718938e+12,0,85176200.0
3405,Zyxel,GS2220-50HP-EU0101F,Network Equipment,ZyXEL Switch GS2220-50HP-EU0101F GS222050HPEU0...,"523,12",1,4.718938e+12,0,85176200.0
3406,Zyxel,XGS2220-30-EU0101F,Network Equipment,Zyxel Switch XGS2220-30-EU0101F XGS222030EU010...,"422,92",6,4.718938e+12,0,85176200.0

In [62]:
df15['Fournisseur'] ='imcopex'
df15= df15[["OEM No.",'Manufacturer',"imcopex Product details",'free stock', 'Customs Tariff number']]
old_names = ["OEM No.",'Manufacturer',"imcopex Product details",'free stock', 'Customs Tariff number']
columns_rename=['Ref_produit','Marque','Description','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df15 = df15.rename(columns=rename_dict)
df15.head(3)

,Ref_produit,Marque,Description,Quantite,Prix
0,100-100000510BOX,AMD,AMD Ryzen 3 4100 3 8 AMD8 AMD 8 GHz (100-10000...,10,84733080.0
1,100-100000031BOX,AMD,AMD Ryzen 5 3600 3 6 AMD6 AMD 6 GHz (100-10000...,15,NaN
2,100-100001489BOX,AMD,AMD Ryzen 5 5500GT 3 6 AMD6 AMD 6 GHz (100-100...,69,84733020.0

In [63]:
file_path=r"/kaggle/input/stp-dataset/tarox (1).csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df16= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df16' in locals():
    print(df16.info())
else:
    print("Failed to load the file with the provided encodings.")

Error with utf-8 encoding: 'utf-8' codec can't decode byte 0xf6 in position 684: invalid start byte
File successfully loaded with ISO-8859-1 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17340 entries, 0 to 17339
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ARCODE           17340 non-null  int64
 1   PG1              17340 non-null  object
 2   PG2              17340 non-null  object
 3   PG3              14037 non-null  object
 4   HerstellerKurz   17339 non-null  object
 5   HerstellerArtNr  17340 non-null  object
 6   Hersteller       17339 non-null  object
 7   EAN              11752 non-null  float64
 8   BezeichnungKurz  17340 non-null  object
 9   Preis            17340 non-null  object
 10  Bestand          17340 non-null  int64
 11  Datenblatt       94 non-null     object
 12  Bild             94 non-null     object
 13  UVP              17340 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 1.9+ MB
None

In [64]:
df16= df16[["HerstellerArtNr","PG2",'Hersteller',"BezeichnungKurz",'HerstellerKurz','Bestand', 'Preis']]
old_names = ["HerstellerArtNr","PG2",'HerstellerKurz',"BezeichnungKurz",'Hersteller','Bestand', 'Preis']
columns_rename=['Ref_produit','Categorie','Marque','Description','Ref_fournisseur','Quantite','Prix']
# Crée un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))
df16 = df16.rename(columns=rename_dict)
df16.head(3)

,Ref_produit,Categorie,Ref_fournisseur,Description,Marque,Quantite,Prix
0,DES-1008D/E,Switch,D-Link,DLINK DES-1008D/E 8-Port Layer2 Fast Ethernet ...,D-Link,0,"9,40"
1,DES-1016D/E,Switch,D-Link,DLINK DES-1016D/E 16-Port Layer2 Fast Ethernet...,D-Link,0,"35,49"
2,33344,Converter / Adapter,InLine,InLine CPU ZB Adapter 3pin an 4pin 33344,InLine,17,"0,84"

In [65]:
file_path=r"/kaggle/input/stp-dataset/terra.csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df17= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df17' in locals():
    print(df17.info())
else:
    print("Failed to load the file with the provided encodings.")

File successfully loaded with utf-8 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11276 entries, 0 to 11275
Data columns (total 47 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ProductId                         11276 non-null  object
 1   ReferenceNo                       10963 non-null  object
 2   EAN                               4432 non-null   float64
 3   Manufacturer                      11275 non-null  object
 4   Price_B2B_Regular                 11276 non-null  object
 5   Price_B2B_Discounted              11276 non-null  object
 6   Price_B2B_DiscountPercent         11276 non-null  int64
 7   Price_B2B_DiscountAmount          11276 non-null  int64
 8   Price_B2C_exclVAT                 11276 non-null  object
 9   Price_B2C_inclVAT                 11276 non-null  object
 10  Price_B2C_VATRate                 11276 non-null  int64
 11  Price_B2C_VATCountry              11276 non-null  object
 12  Price_B2X_Currency                11276 non-null  object
 13  Stock                             11276 non-null  int64
 14  StockNextDelivery                 773 non-null    object
 15  StockNextDeliveryAccessVolume     11276 non-null  int64
 16  WarrantyCode                      4984 non-null   object
 17  EOL                               11276 non-null  int64
 18  Promotion                         11276 non-null  int64
 19  NonReturnable                     11276 non-null  int64
 20  RemainingStock                    11276 non-null  int64
 21  ImagePrimary                      284 non-null    object
 22  ImageAdditional                   192 non-null    object
 23  ProductLink                       0 non-null      float64
 24  GrossWeight                       11276 non-null  object
 25  NetWeight                         0 non-null      float64
 26  RelatedProducts                   302 non-null    object
 27  AccessoryProducts                 1123 non-null   object
 28  Description_1031_German           11275 non-null  object
 29  CategoryName_1031_German          11276 non-null  object
 30  CategoryPath_1031_German          11276 non-null  object
 31  WarrantyDescription_1031_German   4984 non-null   object
 32  Description_1033_English          11275 non-null  object
 33  CategoryName_1033_English         11276 non-null  object
 34  CategoryPath_1033_English         11276 non-null  object
 35  WarrantyDescription_1033_English  1969 non-null   object
 36  Description_1036_French           11275 non-null  object
 37  CategoryName_1036_French          11276 non-null  object
 38  CategoryPath_1036_French          11276 non-null  object
 39  WarrantyDescription_1036_French   3050 non-null   object
 40  Description_1043_Dutch            11275 non-null  object
 41  CategoryName_1043_Dutch           11276 non-null  object
 42  CategoryPath_1043_Dutch           11276 non-null  object
 43  WarrantyDescription_1043_Dutch    1906 non-null   object
 44  ProductDisplayType                11276 non-null  object
 45  LicenseTypeCode                   6218 non-null   object
 46  LicenseTypeDescription            6217 non-null   object
dtypes: float64(3), int64(9), object(35)
memory usage: 4.0+ MB
None

In [66]:
df17

,ProductId,ReferenceNo,EAN,Manufacturer,Price_B2B_Regular,Price_B2B_Discounted,Price_B2B_DiscountPercent,Price_B2B_DiscountAmount,Price_B2C_exclVAT,Price_B2C_inclVAT,...,CategoryName_1036_French,CategoryPath_1036_French,WarrantyDescription_1036_French,Description_1043_Dutch,CategoryName_1043_Dutch,CategoryPath_1043_Dutch,WarrantyDescription_1043_Dutch,ProductDisplayType,LicenseTypeCode,LicenseTypeDescription
0,6540032,FQC-10526,8.898429e+11,Microsoft,"130,9","130,9",0,0,0,0,...,Systèmes d'exploitation,Logiciels|Systèmes d'exploitation,NaN,MS SB Windows 11 Pro 64bit [DK] DVD+++,Operating systemen,Software|Operating systemen,NaN,RegularProduct,MSCOEM,Microsoft System Builder/DSP
1,6481251,021-08709,NaN,Microsoft,122,122,0,0,138,"165,6",...,Applications,Logiciels|Applications,NaN,MS OVL Office Std SA ADD 1Y1Y GOV [D],toepassingen,Software|toepassingen,NaN,RegularProduct,MSOV,Microsoft Open Value
2,3850730,FAN-12CM-T01,4.713214e+12,QNAP,"11,9","11,9",0,0,0,0,...,Accessoires du système,Accessoires|Accessoires du système,NaN,QNAP Gehäuselüfter +++ FAN-12CM-T01,systeemtoebehoren,Toebehoren|systeemtoebehoren,NaN,RegularProduct,NaN,NaN
3,3860412,SG2218P,4.897099e+12,TP-LINK,"204,5","204,5",0,0,0,0,...,Concentrateurs & Commutateurs,Réseau|Concentrateurs & Commutateurs,60 mois garantie retour constructeur,TP-LINK Switch SG2218P 18xGBit/2xSFP Smart Man...,Hubs & Switches,Netwerk|Hubs & Switches,NaN,RegularProduct,NaN,NaN
4,5770037,LC1000C,4.977767e+12,Brother,"9,3","9,3",0,0,0,0,...,Consommables,Consommables,6 mois service retour atelier,Tinte Brother LC-1000C cyan,Verbruikersartikelen,Verbruikersartikelen,6 Maanden service (bring in),RegularProduct,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11271,8001022,MK9540-77A38,5.052179e+12,Honeywell,"69,5","69,5",0,0,0,0,...,Lecteurs de codes à barre,Périphériques|Lecteurs de codes à barre,NaN,Honeywell MS9540 Barcode Scanner USB beige,Barcode-lezer,Randapparatuur|Barcode-lezer,NaN,RegularProduct,NaN,NaN
11272,8001029,MK5145-31A38-EU,5.052179e+12,Honeywell,"42,53","42,53",0,0,0,0,...,Lecteurs de codes à barre,Périphériques|Lecteurs de codes à barre,NaN,Honeywell MS5145 Barcode Scanner Eclipse USB b...,Barcode-lezer,Randapparatuur|Barcode-lezer,NaN,RegularProduct,NaN,NaN
11273,2510380,90YV0GB2-M0NA10,4.711081e+12,Asustek,"245,9","245,9",0,0,0,0,...,Cartes vidéo,Cartes vidéo,36 mois service retour atelier,ASUS VGA 12GB RTX3060 DUAL-O12G-V2 3xDP/HDMI D...,Grafische kaarten,Grafische kaarten,36 Maanden service (bring in),RegularProduct,NaN,NaN
11274,5400380,LS34C650TAUXEN,8.806095e+12,Samsung,445,445,0,0,"646,22","775,46",...,Moniteurs,Moniteurs,36 mois garantie retour constructeur,"Samsung LCD S34C650TAU 34"" white 21:9 ,3.440 x...",Monitoren,Monitoren,NaN,RegularProduct,NaN,NaN
11275,1480375,TERRA MOBILE DOCKING 810,4.039407e+12,WORTMANN AG,209,209,0,0,"293,27","351,92",...,Stations d'accueil,Stations d'accueil,NaN,TERRA MOBILE Dockingstation 810 USB-C/Triple 4...,Dockingstations,Dockingstations,NaN,RegularProduct,NaN,NaN

In [67]:
matching_columns = {
    'ReferenceNo': 'Ref_produit',
    'CategoryName_1033_English':'Categorie',
    'Manufacturer': 'Marque',
    'Description_1033_English':'Description',
    'Stock': 'Quantite',
    'Price_B2B_Regular':'Prix'    
}
# Crée un dictionnaire de renommage
df17 = df17.rename(columns=matching_columns)
df17 = df17[['Ref_produit','Categorie','Marque','Description', 'Quantite', 'Prix']]
df17.head(3)

,Ref_produit,Categorie,Marque,Description,Quantite,Prix
0,FQC-10526,Operating Systems,Microsoft,MS SB Windows 11 Pro 64bit [DK] DVD+++,0,"130,9"
1,021-08709,Applications,Microsoft,MS OVL Office Std SA ADD 1Y1Y GOV [D],100,122
2,FAN-12CM-T01,System Accessories,QNAP,QNAP Gehäuselüfter +++ FAN-12CM-T01,0,"11,9"

In [68]:
file_path=r"/kaggle/input/stp-dataset/travion.csv"
# Liste des encodages à essayer
encodings = ['utf-8', 'ISO-8859-1', 'latin1']

for encoding in encodings:
    try:
        # Tente de lire le fichier CSV avec l'encodage spécifié et un point-virgule comme séparateur
        df18= pd.read_csv(file_path, encoding=encoding, sep=';', on_bad_lines='skip', engine='python')
        print(f"File successfully loaded with {encoding} encoding.")
        break  # Si le fichier est lu avec succès, sortir de la boucle
    except FileNotFoundError:
        print("Error: File not found at", file_path)
        break  # Si le fichier n'est pas trouvé, sortir de la boucle
    except UnicodeDecodeError as e:
        print(f"Error with {encoding} encoding:", e)
    except Exception as e:
        print("Error:", e)

# Vérifiez si le DataFrame a été créé avec succès
if 'df18' in locals():
    print(df18.info())
else:
    print("Failed to load the file with the provided encodings.")

Error with utf-8 encoding: 'utf-8' codec can't decode byte 0xe9 in position 164: invalid continuation byte
File successfully loaded with ISO-8859-1 encoding.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3978 entries, 0 to 3977
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ARTICLENR          3978 non-null   object
 1   OEMNR              3978 non-null   object
 2   EANNR              3516 non-null   float64
 3   UNSPSC             3978 non-null   int64
 4   UNSPSCDESCRIPTION  3978 non-null   object
 5   BRAND              3978 non-null   object
 6   DESCRIPTION        3978 non-null   object
 7   STOCK              3978 non-null   int64
 8   Unnamed: 8         0 non-null      float64
dtypes: float64(2), int64(2), object(5)
memory usage: 279.8+ KB
None

In [69]:
old_names = ["OEMNR", "UNSPSCDESCRIPTION", "BRAND", "DESCRIPTION", "STOCK"]
columns_rename = ['Ref_produit', 'Categorie', 'Marque', 'Description', 'Quantite']

# Créer un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))

# Renommer les colonnes
df18 = df18.rename(columns=rename_dict)
df18=df18[['Ref_produit','Categorie', 'Marque', 'Description', 'Quantite']]
df18.head()

,Ref_produit,Categorie,Marque,Description,Quantite
0,C1000-16FP-2G-L,Commutateurs de réseau,CISCO SYSTEMS,Catalyst 1000 16port GE Full POE - 2x1G SFP,9
1,C1000-16P-E-2G-L,Commutateurs de réseau,CISCO SYSTEMS,Catalyst 1000 16port GE - POE - Ext PS - 2x1G SFP,4
2,C1000-16T-E-2G-L,Commutateurs de réseau,CISCO SYSTEMS,Catalyst 1000 16port GE - Ext PS - 2x1G SFP,1
3,C1000-24FP-4X-L,Commutateurs de réseau,CISCO SYSTEMS,Catalyst 1000 24port GE - Full POE - 4x10G SFP,3
4,C1000-48FP-4X-L,Commutateurs de réseau,CISCO SYSTEMS,Catalyst 1000 48port GE - Full POE - 4x10G SFP,2

In [70]:
df = pd.concat([df0[commun_columns], df2[commun_columns], df4[commun_columns], df6[commun_columns], df7[commun_columns], df12[commun_columns], df13[commun_columns], df14[commun_columns], df15[commun_columns], df16[commun_columns], df17[commun_columns], df18[commun_columns]])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1468890 entries, 0 to 3977
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Ref_produit  1468382 non-null  object
 1   Marque       1468456 non-null  object
 2   Description  1468646 non-null  object
dtypes: object(3)
memory usage: 44.8+ MB

In [71]:
df = pd.concat([df[commun_columns], df8[commun_columns], df9[commun_columns]])
df

       Ref_produit   Marque                                      Description
0          00PA474  2-Power                    Backlit Keyboard (Portuguese)
1          00PA556  2-Power                    Backlit Keyboard (Portuguese)
2     1200G-2USB-1  2-Power                    Voyager 1200g Barcode Scanner
3            1K2CF  2-Power                  Main Battery Pack 15.2V 3941mAh
4       207576-201  2-Power             Blackwire C5220 Stereo USB-A + 3.5mm
...            ...      ...                                              ...
4137     116R00036    Xerox         VersaLink B625 Transfer Roller 116R00036
4138     116R00037    Xerox  VersaLink B625 Bypass Tray Roller Kit 116R00037
4139     116R00035    Xerox   VersaLink B625 Paper Feed Roller Kit 116R00035
4140     115R00161    Xerox             VersaLink B620 Fuser 220 V 115R00161
4141     108R01471    Xerox  Phaser 3330 WC 33xx  Tray 2 Feed Roll 108R01471

[1481267 rows x 3 columns]

In [72]:
df = pd.concat([df[commun_columns], df5[commun_columns]])

In [73]:
df = pd.concat([df[commun_columns], df10[commun_columns]])

In [74]:
df

      Ref_produit   Marque                           Description
0         00PA474  2-Power         Backlit Keyboard (Portuguese)
1         00PA556  2-Power         Backlit Keyboard (Portuguese)
2    1200G-2USB-1  2-Power         Voyager 1200g Barcode Scanner
3           1K2CF  2-Power       Main Battery Pack 15.2V 3941mAh
4      207576-201  2-Power  Blackwire C5220 Stereo USB-A + 3.5mm
..            ...      ...                                   ...
560     006R01518    Xerox                       Xerox 006R01518
561     006R01519    Xerox                       Xerox 006R01519
562     106R02310    Xerox                       Xerox 106R02310
563     106R02773    Xerox                       Xerox 106R02773
564           NaN  Inconnu                                   NaN

[1518665 rows x 3 columns]

In [75]:
df = df.drop_duplicates(subset=['Ref_produit'])
df

         Ref_produit   Marque                           Description
0            00PA474  2-Power         Backlit Keyboard (Portuguese)
1            00PA556  2-Power         Backlit Keyboard (Portuguese)
2       1200G-2USB-1  2-Power         Voyager 1200g Barcode Scanner
3              1K2CF  2-Power       Main Battery Pack 15.2V 3941mAh
4         207576-201  2-Power  Blackwire C5220 Stereo USB-A + 3.5mm
..               ...      ...                                   ...
441           842341    Ricoh                   Ricoh Toner MP 2501
496           408216    Ricoh             Ricoh Toner SPC 352E Cyan
497           408218    Ricoh           Ricoh Toner SPC 352E Yellow
527         MX27GVSA    Sharp        Sharp MX27GVSA Developer C/M/Y
546  MX601B1/MX607B1    Sharp                 Sharp MX601B1/MX607B1

[1438135 rows x 3 columns]

In [76]:
df.describe()

       Ref_produit   Marque Description
count      1438134  1438035     1438082
unique     1438134     1370      900693
top        00PA474   Lenovo   BDPLANAR
freq             1   214514        3748

In [77]:
rows_with_nulls = df[df.isnull().any(axis=1)]
rows_with_nulls

,Ref_produit,Marque,Description
165479,W126638174,Ventev,NaN
165480,W126638175,Ventev,NaN
165481,W126638176,Ventev,NaN
165482,W126638177,Ventev,NaN
269493,W126991623,Lenovo,NaN
...,...,...,...
154975,CE411AC,NaN,HP CONTRACT Cartridge No.305A
155001,01221701,NaN,OKI B930 IMAGE DRUM
155031,CE412AC,NaN,HP 305A TONER YELLOW (2.600 Sheet
11626,DS-D42B02-N,NaN,HIK LED Wall Controller 1.3MP with 2x RJ45 Ports
1276,LNEX1L256GG4,Kioxia Holdings Corporation,NaN

In [78]:
df_concat_cleaned = df.dropna()

In [79]:
df_concat_cleaned

         Ref_produit   Marque                           Description
0            00PA474  2-Power         Backlit Keyboard (Portuguese)
1            00PA556  2-Power         Backlit Keyboard (Portuguese)
2       1200G-2USB-1  2-Power         Voyager 1200g Barcode Scanner
3              1K2CF  2-Power       Main Battery Pack 15.2V 3941mAh
4         207576-201  2-Power  Blackwire C5220 Stereo USB-A + 3.5mm
..               ...      ...                                   ...
441           842341    Ricoh                   Ricoh Toner MP 2501
496           408216    Ricoh             Ricoh Toner SPC 352E Cyan
497           408218    Ricoh           Ricoh Toner SPC 352E Yellow
527         MX27GVSA    Sharp        Sharp MX27GVSA Developer C/M/Y
546  MX601B1/MX607B1    Sharp                 Sharp MX601B1/MX607B1

[1437983 rows x 3 columns]

In [80]:
Kdata=pd.read_csv('/kaggle/input/katia-data/Data1 (1).csv')

In [81]:
Kdata = Kdata[Kdata['Description'] != '0']

In [82]:
Kdata.describe()

       Ref_produit  Marque                      Description
count       548702  548218                           541479
unique      548702   10520                           399204
top         US221A   APPLE  1YR SUBSCRIPTION WITH 1YR
freq             1   57620                             1230

In [83]:
Kdata= Kdata.dropna()
Kdata.describe()

       Ref_produit  Marque                      Description
count       541293  541293                           541293
unique      541293   10467                           399028
top         US221A   APPLE  1YR SUBSCRIPTION WITH 1YR
freq             1   57619                             1230

In [84]:
Kdata

,Ref_produit,Marque,Description
0,US221A,Aten,ATEN US-221 - USB peripheral sharing switch - ...
1,AEMNT00049A,Arctic Cooling,ARCTIC Z1 Pro (Gen 3) - mounting kit
2,AEMNT00050A,Arctic Cooling,ARCTIC Z2 Pro - mounting kit
3,AEMNT00051A,Arctic Cooling,ARCTIC Z3 Pro (Gen 3) - mounting kit
4,939-001644,Logitech,Logitech Rally - video conferencing mounting kit
...,...,...,...
550990,zxp7ymckok2,ZEBRA,Zebra ZXP 7 Series colour ribbon Zebra ZXP Ser...
550991,zxp7ymcuvk,ZEBRA,Zebra ZXP 7 Series colour ribbon Zebra ZXP Ser...
550992,zxp9-16,ZEBRA,"Zebra ZXP Series 9, deux faces, 12 pts/mm (300..."
550993,zxplamt,ZEBRA,"Zebra lamination ribbon Lamination ribbon, 1 m..."
550994,zxplamt2,ZEBRA,"Zebra lamination ribbon Lamination ribbon, 1 m..."

In [85]:
df = pd.concat([df[commun_columns], Kdata[commun_columns]])
df

,Ref_produit,Marque,Description
0,00PA474,2-Power,Backlit Keyboard (Portuguese)
1,00PA556,2-Power,Backlit Keyboard (Portuguese)
2,1200G-2USB-1,2-Power,Voyager 1200g Barcode Scanner
3,1K2CF,2-Power,Main Battery Pack 15.2V 3941mAh
4,207576-201,2-Power,Blackwire C5220 Stereo USB-A + 3.5mm
...,...,...,...
550990,zxp7ymckok2,ZEBRA,Zebra ZXP 7 Series colour ribbon Zebra ZXP Ser...
550991,zxp7ymcuvk,ZEBRA,Zebra ZXP 7 Series colour ribbon Zebra ZXP Ser...
550992,zxp9-16,ZEBRA,"Zebra ZXP Series 9, deux faces, 12 pts/mm (300..."
550993,zxplamt,ZEBRA,"Zebra lamination ribbon Lamination ribbon, 1 m..."
550994,zxplamt2,ZEBRA,"Zebra lamination ribbon Lamination ribbon, 1 m..."

In [86]:
df = df.drop_duplicates(subset=['Ref_produit'])
df

,Ref_produit,Marque,Description
0,00PA474,2-Power,Backlit Keyboard (Portuguese)
1,00PA556,2-Power,Backlit Keyboard (Portuguese)
2,1200G-2USB-1,2-Power,Voyager 1200g Barcode Scanner
3,1K2CF,2-Power,Main Battery Pack 15.2V 3941mAh
4,207576-201,2-Power,Blackwire C5220 Stereo USB-A + 3.5mm
...,...,...,...
550990,zxp7ymckok2,ZEBRA,Zebra ZXP 7 Series colour ribbon Zebra ZXP Ser...
550991,zxp7ymcuvk,ZEBRA,Zebra ZXP 7 Series colour ribbon Zebra ZXP Ser...
550992,zxp9-16,ZEBRA,"Zebra ZXP Series 9, deux faces, 12 pts/mm (300..."
550993,zxplamt,ZEBRA,"Zebra lamination ribbon Lamination ribbon, 1 m..."
550994,zxplamt2,ZEBRA,"Zebra lamination ribbon Lamination ribbon, 1 m..."

In [87]:
df.describe()

       Ref_produit   Marque Description
count      1873648  1873549     1873596
unique     1873648     4335     1206417
top        00PA474   Lenovo   BDPLANAR
freq             1   215457        3748

In [88]:
df.to_csv('clean_data.csv', index=False)

In [89]:
dfcat2=pd.read_csv('/kaggle/input/part2-icecat/132234_FR.csv')
dfcat2.info()

/tmp/ipykernel_18/790688318.py:1: DtypeWarning: Columns (22,23,29,30,31,32,36,37,38,39,40,41,42,44,45,46,47,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271) have mixed types. Specify dtype option on import or set low_memory=False.
  dfcat2=pd.read_csv('/kaggle/input/part2-icecat/132234_FR.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269782 entries, 0 to 269781
Columns: 272 entries, Requested_prod_id to Specs 224
dtypes: float64(6), int64(1), object(265)
memory usage: 559.9+ MB

In [90]:
# Liste des colonnes à supprimer
columns_to_drop = [
    22, 23, 29, 30, 31, 32, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47,
    211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224,
    225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
    239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
    253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266,
    267, 268, 269, 270, 271
]

# Convertir les indices de colonnes en noms de colonnes
columns_to_drop = [dfcat2.columns[i] for i in columns_to_drop]

# Supprimer les colonnes
dfcat2.drop(columns=columns_to_drop, inplace=True)

# Afficher les informations sur le DataFrame
dfcat2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269782 entries, 0 to 269781
Columns: 194 entries, Requested_prod_id to Specs 163
dtypes: float64(6), int64(1), object(187)
memory usage: 399.3+ MB

In [91]:
additional_columns_to_drop = [
    'Specs 1', 'Specs 2', 'Specs 3', 'Specs 4', 'Specs 5',
       'Specs 6', 'Specs 7', 'Specs 8', 'Specs 9', 'Specs 10', 'Specs 11',
       'Specs 12', 'Specs 13', 'Specs 14', 'Specs 15', 'Specs 16', 'Specs 17',
       'Specs 18', 'Specs 19', 'Specs 20', 'Specs 21', 'Specs 22', 'Specs 23',
       'Specs 24', 'Specs 25', 'Specs 26', 'Specs 27', 'Specs 28', 'Specs 29',
       'Specs 30', 'Specs 31', 'Specs 32', 'Specs 33', 'Specs 34', 'Specs 35',
       'Specs 36', 'Specs 37', 'Specs 38', 'Specs 39', 'Specs 40', 'Specs 41',
       'Specs 42', 'Specs 43', 'Specs 44', 'Specs 45', 'Specs 46', 'Specs 47',
       'Specs 48', 'Specs 49', 'Specs 50', 'Specs 51', 'Specs 52', 'Specs 53',
       'Specs 54', 'Specs 55', 'Specs 56', 'Specs 57', 'Specs 58', 'Specs 59',
       'Specs 60', 'Specs 61', 'Specs 62', 'Specs 63', 'Specs 64', 'Specs 65',
       'Specs 66'
]

# Combiner les deux listes de colonnes à supprimer
columns_to_drop.extend(additional_columns_to_drop)

# Vérifier l'existence des colonnes avant de les supprimer
columns_to_drop = [col for col in columns_to_drop if col in dfcat2.columns]

# Supprimer les colonnes
dfcat2.drop(columns=columns_to_drop, inplace=True)
dfcat2.head(3)

,Requested_prod_id,Requested_GTIN(EAN/UPC),Requested_Icecat_id,ErrorMessage,Supplier,Prod_id,Icecat_id,GTIN(EAN/UPC),Category,CatId,...,Specs 154,Specs 155,Specs 156,Specs 157,Specs 158,Specs 159,Specs 160,Specs 161,Specs 162,Specs 163
0,T6208AAE,NaN,4003037,NaN,HP,T6208AAE,4003037.0,NaN,Non classé,1170.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,VT122PA,NaN,4003047,NaN,HP,VT122PA,4003047.0,NaN,Laptops,151.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VT491AA,NaN,4003049,NaN,HP,VT491AA,4003049.0,NaN,Claviers,194.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
dfcat2.columns

Index(['Requested_prod_id', 'Requested_GTIN(EAN/UPC)', 'Requested_Icecat_id',
       'ErrorMessage', 'Supplier', 'Prod_id', 'Icecat_id', 'GTIN(EAN/UPC)',
       'Category', 'CatId',
       ...
       'Specs 154', 'Specs 155', 'Specs 156', 'Specs 157', 'Specs 158',
       'Specs 159', 'Specs 160', 'Specs 161', 'Specs 162', 'Specs 163'],
      dtype='object', length=128)

In [93]:
# Sélectionner uniquement les colonnes spécifiées
selected_columns = ['Requested_prod_id', 'LongSummaryDescription', 'Supplier']

# Vérifier que les colonnes existent dans le DataFrame
selected_columns = [col for col in selected_columns if col in dfcat2.columns]

# Afficher les colonnes sélectionnées
dfcat2_selected = dfcat2[selected_columns]

# Afficher les informations et les premières lignes du DataFrame résultant
dfcat2_selected.info()
dfcat2_selected.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269782 entries, 0 to 269781
Data columns (total 3 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Requested_prod_id       269782 non-null  object
 1   LongSummaryDescription  238251 non-null  object
 2   Supplier                269782 non-null  object
dtypes: object(3)
memory usage: 6.2+ MB

,Requested_prod_id,LongSummaryDescription,Supplier
0,T6208AAE,HP BAC SLM for Business Process Monitor 200+ T...,HP
1,VT122PA,HP Mini 110-1101TU PC,HP
2,VT491AA,HP VT491AA. Facteur de forme du clavier: Taill...,HP
3,VV357PA,HP Compaq Presario CQ61-318TX Notebook PC,HP
4,FL963UT,HP xw4600 Workstation,HP

In [94]:
old_names = ['Requested_prod_id', 'LongSummaryDescription', 'Supplier']
columns_rename = ['Ref_produit', 'Description','Marque']

# Créer un dictionnaire de renommage
rename_dict = dict(zip(old_names, columns_rename))

# Renommer les colonnes
dfcat2_selected = dfcat2_selected.rename(columns=rename_dict)
#dfcat2_selected=dfcat2_selected['Ref_produit', 'Description','Marque']]
dfcat2_selected.head()

  Ref_produit                                        Description Marque
0    T6208AAE  HP BAC SLM for Business Process Monitor 200+ T...     HP
1     VT122PA                              HP Mini 110-1101TU PC     HP
2     VT491AA  HP VT491AA. Facteur de forme du clavier: Taill...     HP
3     VV357PA          HP Compaq Presario CQ61-318TX Notebook PC     HP
4     FL963UT                              HP xw4600 Workstation     HP

In [95]:
dfcat2_selected = dfcat2_selected.drop_duplicates(subset=['Ref_produit'])

In [96]:
dfcat2_selected= dfcat2_selected.dropna()
dfcat2_selected.describe()

       Ref_produit                              Description  Marque
count       218761                                   218761  218761
unique      218761                                   190137     209
top       T6208AAE  HP 1y 24x7 ProCurve Wireless SW Support      HP
freq             1                                      349   27504

In [97]:
dfcat2_selected.to_csv('dfcat2_clean.csv', index=False)

In [98]:
dfcat2_selected.to_csv('dfcat2_clean.xlsx', index=False)